import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../src/simulation.js';
import {metrics} from '../src/metrics.js';
import {findPath} from '../src/pathfinding.js';
import {enqueue,processQueue,startService} from '../src/queueSystem.js';
import {actionPoint,isWalkable} from '../src/journey.js';

test('all rooms are connected through the corridor graph',()=>{const s=new Simulation();for(const a of s.rooms)for(const b of s.rooms){const path=findPath(s.graph,a.id,b.id);assert.equal(path[0],s.graph[a.id]);assert.equal(path.at(-1),s.graph[b.id]);}});
test('ticketed journey includes both waiting visits, pulse, lab results and return to the same doctor',()=>{const s=new Simulation();s.nextArrival=Infinity;const p=s.spawn();for(let i=0;i<6000&&p.phase!=='done';i++)s.step();assert.equal(p.state,'DISCHARGED');assert.equal(p.ticket,'T001');assert.equal(p.doctorVisits,2);assert.ok(p.pulse.bpm>=65&&p.pulse.bpm<=100);assert.ok(p.results.reviewedAt>p.results.readyAt);const visited=p.history.filter(e=>e.type==='Entered').map(e=>e.room);assert.deepEqual(visited,['Entrance & tickets','Reception','Waiting room','Triage','Waiting room','Consultation 01','Laboratory','Consultation 01','Pharmacy','Exit']);assert.ok(s.rooms.every(r=>!r.queue.length&&!r.occupants.length&&!r.called.length));assert.equal(metrics(s).discharged,1);});
test('clock pauses and speed preserves deterministic simulation results',()=>{const a=new Simulation(),b=new Simulation();a.advance(20);assert.equal(a.time,0);a.running=b.running=true;a.speed=1;b.speed=100;a.advance(3600);b.advance(36);assert.deepEqual(a.patients,b.patients);a.running=false;a.advance(10);assert.equal(a.time,3600);});
test('priority calls reserve capacity before patients arrive',()=>{const r={queue:[],called:[],occupants:[],capacity:1,serviceTime:20};const routine={priority:'Routine',id:1,waitingTime:0},urgent={priority:'Urgent',id:2,waitingTime:0},critical={priority:'Critical',id:3,waitingTime:0,stage:1};enqueue(r,routine,1);enqueue(r,urgent,2);enqueue(r,critical,3);processQueue(r,10,()=>{});assert.equal(r.called[0],critical);assert.equal(critical.waitingTime,7);processQueue(r,11,()=>{});assert.equal(r.called.length,1);assert.deepEqual(r.queue.map(p=>p.id),[2,1]);startService(r,critical,12);assert.equal(r.occupants[0],critical);assert.equal(r.called.length,0);});
test('patients actually wait centrally until called',()=>{const s=new Simulation();s.nextArrival=Infinity;s.room('triage').capacity=0;const p=s.spawn();for(let i=0;i<400;i++)s.step();assert.equal(p.stage,3);assert.equal(p.phase,'queued');assert.equal(p.currentRoom,'waiting');assert.equal(s.room('triage').queue[0],p);s.room('triage').capacity=1;s.step();assert.ok(['moving','service'].includes(p.phase));assert.ok(s.calls.some(c=>c.ticket===p.ticket&&c.roomId==='triage'));});
test('lab releases its slot during results processing and results wait contributes to metrics',()=>{const s=new Simulation();s.nextArrival=Infinity;const p=s.spawn();while(p.phase!=='results'&&s.time<5000)s.step();assert.equal(p.phase,'results');assert.equal(s.room('lab').occupants.length,0);const before=metrics(s).avgWait;for(let i=0;i<30;i++)s.step();assert.equal(metrics(s).waiting,1);assert.equal(metrics(s).avgWait,before+30);});
test('busy run conserves patients and reserves only available slots',()=>{const s=new Simulation();for(let i=0;i<7200;i++){s.step();for(const r of s.rooms)assert.ok(r.occupants.length+r.called.length<=r.capacity);for(const p of s.patients)assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.y));}const m=metrics(s);assert.equal(m.arrivals,m.active+m.discharged);assert.ok(m.discharged>0);assert.ok(m.waiting>0);});
test('one-player mode creates exactly one controllable person with no automatic arrivals',()=>{const s=new Simulation(42,'player');const p=s.player;for(let i=0;i<1000;i++)s.step();assert.equal(s.patients.length,1);assert.equal(s.spawn(),p);assert.equal(p.stage,0);assert.equal(p.phase,'exploring');assert.equal(p.ticket,null);s.running=true;const old=p.y;assert.ok(s.movePlayer(0,10));assert.equal(p.y,old+10);s.running=false;assert.equal(s.movePlayer(0,10),false);});
test('player must interact near each station and can complete all steps using assisted walking',()=>{const s=new Simulation(42,'player');s.running=true;const p=s.player;assert.match(s.interact(),/Move closer/);assert.equal(p.ticket,null);for(let i=0;i<50&&p.phase!=='done';i++){if(['exploring','called'].includes(p.phase)){assert.ok(s.walkPlayer());while(p.phase==='moving')s.step();}else if(['queued','service','results'].includes(p.phase))assert.ok(s.skipPlayerWait());else assert.fail(p.phase);}assert.equal(p.phase,'done');assert.equal(s.patients.length,1);assert.equal(p.doctorVisits,2);assert.ok(p.results.reviewedAt!==null);});
test('doorway navigation blocks crossing side walls and admits through doors',()=>{const s=new Simulation();const r=s.room('triage');assert.equal(isWalkable(s.rooms,r.x,r.y+80),false);assert.equal(isWalkable(s.rooms,r.x+20,r.y+r.height),false);assert.equal(isWalkable(s.rooms,r.x+r.width/2,r.y+r.height),true);const p=s.spawn();p.currentRoom='reception';p.x=75;p.y=210;s.route(p,'triage');assert.deepEqual(p.path[0],actionPoint(s.room('reception'),1));});
test('a patient counts as discharged only after reaching the exit',()=>{const s=new Simulation();s.nextArrival=Infinity;const p=s.spawn();while(p.stage!==10&&s.time<6000)s.step();assert.equal(p.state,'LEAVING');assert.equal(p.dischargeTime,null);assert.equal(metrics(s).active,1);assert.equal(metrics(s).discharged,0);assert.equal(metrics(s).los,0);while(p.phase!=='done')s.step();assert.equal(metrics(s).discharged,1);assert.ok(p.dischargeTime>0);});
